import { CivicDataAccessMethod, SourceType } from "@prisma/client";

import type { CivicSourceDefinition } from "@/lib/civic-data/types";

export const NEVADA_BETA_SOURCE_DEFINITIONS: CivicSourceDefinition[] = [
  {
    name: "Nevada Electronic Legislative Information System",
    slug: "nevada-legislature-nelis",
    sourceType: SourceType.LEGISLATIVE_API,
    url: "https://www.leg.state.nv.us/Redir/toCurrentNELIS.cfm",
    adapterKey: "nevada-legislature",
    jurisdictionSlug: "nevada",
    dataCategory: "legislative_bills_votes_officials",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 6,
    refreshFrequency: "weekly",
    description: "Nevada Legislature bills, sponsors, committees, meetings, agendas, and votes.",
  },
  {
    name: "Nevada Secretary of State Elections",
    slug: "nevada-secretary-of-state-elections",
    sourceType: SourceType.ELECTIONS_PORTAL,
    url: "https://www.nvsos.gov/sos/elections",
    adapterKey: "nevada-secretary-of-state",
    jurisdictionSlug: "nevada",
    dataCategory: "candidate_filings_elections_campaign_finance",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 1,
    refreshFrequency: "daily_during_election_season",
    description: "Statewide elections, candidates, ballot questions, and campaign finance filings.",
  },
  {
    name: "Nevada Secretary of State Voter Registration Statistics",
    slug: "nevada-secretary-of-state-voter-registration-statistics",
    sourceType: SourceType.ELECTIONS_PORTAL,
    url: "https://www.nvsos.gov/sos/elections/voters/voter-registration-statistics",
    adapterKey: "nevada-secretary-of-state",
    jurisdictionSlug: "nevada",
    dataCategory: "voter_registration_statistics",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 1,
    refreshFrequency: "monthly",
    description: "Nevada SOS statewide and county voter registration statistics. Parser implementation is pending; source remains registered for scheduled checks.",
  },
  {
    name: "Nevada Secretary of State Election Results",
    slug: "nevada-secretary-of-state-election-results",
    sourceType: SourceType.ELECTIONS_PORTAL,
    url: "https://www.nvsos.gov/sos/elections/election-results",
    adapterKey: "nevada-secretary-of-state",
    jurisdictionSlug: "nevada",
    dataCategory: "election_results",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 2,
    refreshFrequency: "daily_during_election_season",
    description: "Nevada SOS official election result publications and canvass data.",
  },
  {
    name: "Nevada Secretary of State Precinct-Level Results",
    slug: "nevada-secretary-of-state-precinct-results",
    sourceType: SourceType.ELECTIONS_PORTAL,
    url: "https://www.nvsos.gov/sos/elections/election-results",
    adapterKey: "nevada-secretary-of-state",
    jurisdictionSlug: "nevada",
    dataCategory: "precinct_results",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 3,
    refreshFrequency: "daily_during_election_season",
    description: "Nevada SOS precinct-level results registration for future precinct parser imports.",
  },
  {
    name: "Nevada Secretary of State Candidate Filings",
    slug: "nevada-secretary-of-state-candidate-filings",
    sourceType: SourceType.ELECTIONS_PORTAL,
    url: "https://www.nvsos.gov/sos/elections/candidate-information",
    adapterKey: "nevada-secretary-of-state",
    jurisdictionSlug: "nevada",
    dataCategory: "candidate_filings",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 1,
    refreshFrequency: "daily_during_election_season",
    description: "Nevada SOS candidate filing and ballot-status records.",
  },
  {
    name: "State of Nevada Constitutional Officers",
    slug: "nevada-state-government-officials",
    sourceType: SourceType.GOVERNMENT_PORTAL,
    url: "https://nv.gov/",
    adapterKey: "nevada-state-government",
    jurisdictionSlug: "nevada",
    dataCategory: "officials",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 8,
    refreshFrequency: "weekly",
    description: "Nevada statewide elected executive offices and current officeholders from official state websites.",
  },
  {
    name: "Nevada Federal Delegation",
    slug: "nevada-federal-delegation",
    sourceType: SourceType.GOVERNMENT_PORTAL,
    url: "https://www.congress.gov/members/find-your-member",
    adapterKey: "nevada-federal-delegation",
    jurisdictionSlug: "nevada",
    dataCategory: "federal_officials",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 8,
    refreshFrequency: "weekly",
    description: "Nevada U.S. Senators and U.S. Representatives from official congressional websites.",
  },
  {
    name: "City of Reno Government",
    slug: "reno-government",
    sourceType: SourceType.MUNICIPAL_PORTAL,
    url: "https://www.reno.gov/government",
    adapterKey: "reno",
    jurisdictionSlug: "reno",
    dataCategory: "municipal_officials_meetings_wards",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 9,
    refreshFrequency: "weekly",
    description: "Reno offices, officials, council meetings, agendas, and local civic records.",
  },
  {
    name: "Carson City Government",
    slug: "carson-city-government",
    sourceType: SourceType.MUNICIPAL_PORTAL,
    url: "https://www.carson.org/",
    adapterKey: "carson-city",
    jurisdictionSlug: "carson-city",
    dataCategory: "local_elections_officials_meetings",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 5,
    refreshFrequency: "weekly",
    description: "Carson City offices, elections, meetings, agendas, and local government records.",
  },
  {
    name: "Washoe County Government",
    slug: "washoe-county-government",
    sourceType: SourceType.COUNTY_PORTAL,
    url: "https://www.washoecounty.gov/",
    adapterKey: "washoe-county",
    jurisdictionSlug: "washoe-county",
    dataCategory: "county_officials_commission_districts",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 4,
    refreshFrequency: "weekly",
    description: "Washoe County commissioners, departments, meetings, agendas, and county records.",
  },
  {
    name: "Clark County Elections",
    slug: "clark-county-elections",
    sourceType: SourceType.COUNTY_PORTAL,
    url: "https://www.clarkcountynv.gov/government/departments/elections/",
    adapterKey: "county-election-office",
    jurisdictionSlug: "clark-county",
    dataCategory: "county_elections_results_precincts",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 4,
    refreshFrequency: "daily_during_election_season",
    description: "Clark County election office records, candidates, results, and voter information.",
  },
  ...[
    ["churchill-county-elections", "Churchill County Elections", "churchill-county", "https://www.churchillcountynv.gov/"],
    ["douglas-county-elections", "Douglas County Elections", "douglas-county", "https://cltr.douglascountynv.gov/"],
    ["elko-county-elections", "Elko County Elections", "elko-county", "https://www.elkocountynv.net/"],
    ["esmeralda-county-elections", "Esmeralda County Elections", "esmeralda-county", "https://www.accessesmeralda.com/"],
    ["eureka-county-elections", "Eureka County Elections", "eureka-county", "https://www.co.eureka.nv.us/"],
    ["humboldt-county-elections", "Humboldt County Elections", "humboldt-county", "https://www.humboldtcountynv.gov/"],
    ["lander-county-elections", "Lander County Elections", "lander-county", "https://www.landercountynv.org/"],
    ["lincoln-county-elections", "Lincoln County Elections", "lincoln-county", "https://lincolncountynv.gov/"],
    ["lyon-county-elections", "Lyon County Elections", "lyon-county", "https://www.lyon-county.org/"],
    ["mineral-county-elections", "Mineral County Elections", "mineral-county", "https://www.mineralcountynv.us/"],
    ["nye-county-elections", "Nye County Elections", "nye-county", "https://www.nyecountynv.gov/"],
    ["pershing-county-elections", "Pershing County Elections", "pershing-county", "https://pershingcountynv.gov/"],
    ["storey-county-elections", "Storey County Elections", "storey-county", "https://www.storeycounty.org/"],
    ["white-pine-county-elections", "White Pine County Elections", "white-pine-county", "https://www.whitepinecounty.net/"],
  ].map(([slug, name, jurisdictionSlug, url]) => ({
    name,
    slug,
    sourceType: SourceType.COUNTY_PORTAL,
    url,
    adapterKey: "county-election-office" as const,
    jurisdictionSlug,
    dataCategory: "county_elections_results_precincts",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 7,
    refreshFrequency: "daily_during_election_season",
    description: `${name} source registration for future county election imports. Parser implementation is pending.`,
  })),
  {
    name: "Washoe County Voter Data Portal",
    slug: "washoe-county-voter-data",
    sourceType: SourceType.COUNTY_PORTAL,
    url: "https://www.washoecounty.gov/voters/data/index.php",
    adapterKey: "county-election-office",
    jurisdictionSlug: "washoe-county",
    dataCategory: "local_candidates_results_registration_precincts",
    accessMethod: CivicDataAccessMethod.html,
    importPriority: 2,
    refreshFrequency: "weekly",
    description: "Washoe election data, registration reports, archived results, and public local election data.",
    notes: "Use with Washoe open data and ArcGIS boundary layers for district-aware matching.",
  },
  {
    name: "Washoe Open Data Boundaries",
    slug: "washoe-open-data-boundaries",
    sourceType: SourceType.COUNTY_PORTAL,
    url: "https://gis.washoecounty.us/open-data/",
    adapterKey: "arcgis-boundaries",
    jurisdictionSlug: "washoe-county",
    dataCategory: "district_boundaries_precincts",
    accessMethod: CivicDataAccessMethod.arcgis,
    importPriority: 2,
    refreshFrequency: "weekly",
    description: "Washoe precinct, commission, municipal, school, and district boundary layers for district-aware matching.",
    notes: "Parser is a registered stub until layer URLs are pinned and reviewed.",
  },
  {
    name: "OpenStates Nevada API",
    slug: "openstates-nevada-api",
    sourceType: SourceType.LEGISLATIVE_API,
    url: "https://docs.openstates.org/api-v3/",
    adapterKey: "openstates",
    jurisdictionSlug: "nevada",
    dataCategory: "legislative_officials_bills_votes",
    accessMethod: CivicDataAccessMethod.api,
    importPriority: 6,
    refreshFrequency: "weekly_during_session",
    description: "Normalized legislative backup source for Nevada legislators, bills, committees, sponsors, and votes.",
    notes: "Requires API configuration before records import.",
  },
  {
    name: "Plural Open Data",
    slug: "plural-open-data",
    sourceType: SourceType.LEGISLATIVE_API,
    url: "https://open.pluralpolicy.com/data/",
    adapterKey: "nevada-legislature-records",
    jurisdictionSlug: "nevada",
    dataCategory: "legislative_open_data",
    accessMethod: CivicDataAccessMethod.api,
    importPriority: 7,
    refreshFrequency: "weekly_during_session",
    description: "Legislative open data candidate for bill, sponsor, vote, and committee cross-checks.",
    notes: "Evaluation source; conflicts must route to pending review.",
  },
  {
    name: "LegiScan Nevada Datasets",
    slug: "legiscan-nevada-datasets",
    sourceType: SourceType.LEGISLATIVE_API,
    url: "https://legiscan.com/NV/datasets",
    adapterKey: "nevada-legislature-records",
    jurisdictionSlug: "nevada",
    dataCategory: "legislative_dataset_crosscheck",
    accessMethod: CivicDataAccessMethod.manual_download,
    importPriority: 8,
    refreshFrequency: "weekly_during_session",
    description: "Downloaded legislative dataset option for Nevada bill and vote cross-checking.",
    notes: "Do not import until licensing/access terms and field mapping are reviewed.",
  },
];

export function getSourceDefinition(slug: string) {
  return NEVADA_BETA_SOURCE_DEFINITIONS.find((source) => source.slug === slug);
}
