import { getCommunityById } from "@/lib/community/communities";
import type { ServiceCategory, ServiceSummary } from "@/types/domain";

const seededServices: ServiceSummary[] = [
  {
    id: "service_carson_housing",
    title: "Find housing and homelessness resources",
    description: "Use Carson City community support resources for housing assistance, shelter, and related services.",
    category: "Housing",
    externalLink: "https://www.carson.org/communitysupportservices",
    jurisdictionId: "carson-city",
    jurisdictionName: "Carson City, Nevada",
    responsibleEntity: "Carson City Community Support Services",
    responsibleOfficialId: "profile_elena_ramirez",
    relatedIssue: "Housing affordability",
    createdAt: "2026-04-01T07:55:00.000Z",
  },
  {
    id: "service_carson_pothole",
    title: "Report a pothole",
    description: "Use Carson City public works contacts to report road damage and street maintenance needs.",
    category: "Transportation",
    externalLink: "https://www.carson.org/publicworks",
    jurisdictionId: "carson-city",
    jurisdictionName: "Carson City, Nevada",
    responsibleEntity: "Carson City Public Works",
    responsibleOfficialId: "profile_elena_ramirez",
    relatedIssue: "Infrastructure",
    createdAt: "2026-04-01T08:00:00.000Z",
  },
  {
    id: "service_carson_school_enrollment",
    title: "Enroll in school",
    description: "Find Carson City School District registration information, school contacts, and enrollment steps.",
    category: "Education",
    externalLink: "https://www.carsoncityschools.com/parents/enrollment",
    jurisdictionId: "carson-city",
    jurisdictionName: "Carson City, Nevada",
    responsibleEntity: "Carson City School District",
    responsibleOfficialId: "profile_owen_castillo",
    relatedIssue: "Education funding",
    createdAt: "2026-04-01T08:05:00.000Z",
  },
  {
    id: "service_carson_permits",
    title: "Apply for permits",
    description: "Start local development, building, and engineering permit tasks through Carson City resources.",
    category: "Permits",
    externalLink: "https://www.carson.org/communitydevelopment",
    jurisdictionId: "carson-city",
    jurisdictionName: "Carson City, Nevada",
    responsibleEntity: "Carson City Community Development",
    responsibleOfficialId: "profile_elena_ramirez",
    relatedIssue: "Downtown growth",
    createdAt: "2026-04-01T08:10:00.000Z",
  },
  {
    id: "service_carson_utilities",
    title: "Pay utilities",
    description: "Access Carson City utility billing for water, sewer, storm water, and account management.",
    category: "Utilities",
    externalLink: "https://www.carson.org/utilitybilling",
    jurisdictionId: "carson-city",
    jurisdictionName: "Carson City, Nevada",
    responsibleEntity: "Carson City Public Works - Utility Billing",
    responsibleOfficialId: "profile_elena_ramirez",
    relatedIssue: "Water planning",
    createdAt: "2026-04-01T08:15:00.000Z",
  },
  {
    id: "service_carson_safety",
    title: "Find non-emergency public safety contacts",
    description: "Reach Carson City Sheriff and city public safety contacts for non-emergency reporting and records guidance.",
    category: "Public Safety",
    externalLink: "https://www.carson.org/sheriff",
    jurisdictionId: "carson-city",
    jurisdictionName: "Carson City, Nevada",
    responsibleEntity: "Carson City Sheriff's Office",
    responsibleOfficialId: null,
    relatedIssue: "Public safety",
    createdAt: "2026-04-01T08:17:00.000Z",
  },
  {
    id: "service_nevada_vote_registration",
    title: "Register to vote",
    description: "Go to Nevada’s official voter registration resources and election information.",
    category: "Public Safety",
    externalLink: "https://www.nvsos.gov/sos/elections",
    jurisdictionId: "nevada",
    jurisdictionName: "Nevada",
    responsibleEntity: "Nevada Secretary of State",
    responsibleOfficialId: null,
    relatedIssue: "Government transparency",
    createdAt: "2026-04-01T08:20:00.000Z",
  },
  {
    id: "service_nevada_business_licensing",
    title: "Business licensing",
    description: "Start or manage Nevada business filings and licensing through the state’s business portal.",
    category: "Permits",
    externalLink: "https://www.nvsilverflume.gov/home",
    jurisdictionId: "nevada",
    jurisdictionName: "Nevada",
    responsibleEntity: "Nevada SilverFlume Business Portal",
    responsibleOfficialId: null,
    relatedIssue: "Economic development",
    createdAt: "2026-04-01T08:25:00.000Z",
  },
  {
    id: "service_reno_housing",
    title: "Find housing help in Reno",
    description: "Use Reno-area housing and community assistance resources for shelter, support, and local services.",
    category: "Housing",
    externalLink: "https://www.reno.gov/community/homelessness",
    jurisdictionId: "reno",
    jurisdictionName: "Washoe County, Nevada",
    responsibleEntity: "City of Reno Housing and Neighborhood Services",
    responsibleOfficialId: "profile_david_park",
    relatedIssue: "Housing affordability",
    createdAt: "2026-04-01T08:28:00.000Z",
  },
  {
    id: "service_reno_pothole",
    title: "Report a Reno street issue",
    description: "Use City of Reno service resources for street damage, traffic signs, and maintenance requests.",
    category: "Transportation",
    externalLink: "https://www.reno.gov/government/departments/public-works",
    jurisdictionId: "reno",
    jurisdictionName: "Washoe County, Nevada",
    responsibleEntity: "City of Reno Public Works",
    responsibleOfficialId: "profile_david_park",
    relatedIssue: "Road safety",
    createdAt: "2026-04-01T08:30:00.000Z",
  },
  {
    id: "service_reno_utilities",
    title: "Manage utility services",
    description: "Find utility and public works billing information relevant to Reno-area residents.",
    category: "Utilities",
    externalLink: "https://www.reno.gov/government/departments/public-works",
    jurisdictionId: "reno",
    jurisdictionName: "Washoe County, Nevada",
    responsibleEntity: "Reno Public Works",
    responsibleOfficialId: "profile_david_park",
    relatedIssue: "Water resilience",
    createdAt: "2026-04-01T08:35:00.000Z",
  },
  {
    id: "service_national_vote_info",
    title: "Find national voting information",
    description: "Use USA.gov to find voter registration and election guidance by state.",
    category: "Public Safety",
    externalLink: "https://www.usa.gov/voter-registration",
    jurisdictionId: "united-states",
    jurisdictionName: "United States",
    responsibleEntity: "USA.gov",
    responsibleOfficialId: null,
    relatedIssue: "Government transparency",
    createdAt: "2026-04-01T08:40:00.000Z",
  },
  {
    id: "service_unr_registrar",
    title: "Registrar and enrollment support",
    description: "Find enrollment, registration, transcript, and academic calendar help through UNR registrar resources.",
    category: "Education",
    externalLink: "https://www.unr.edu/registrar",
    jurisdictionId: "unr-campus",
    jurisdictionName: "University of Nevada, Reno",
    responsibleEntity: "UNR Office of the Registrar",
    responsibleOfficialId: null,
    relatedIssue: "Enrollment and registration",
    createdAt: "2026-04-01T08:45:00.000Z",
  },
  {
    id: "service_unr_financial_aid",
    title: "Financial aid and scholarships",
    description: "Use UNR financial aid resources for FAFSA support, scholarships, and student account guidance.",
    category: "Education",
    externalLink: "https://www.unr.edu/financial-aid",
    jurisdictionId: "unr-campus",
    jurisdictionName: "University of Nevada, Reno",
    responsibleEntity: "UNR Financial Aid and Scholarships",
    responsibleOfficialId: null,
    relatedIssue: "Student affordability",
    createdAt: "2026-04-01T08:47:00.000Z",
  },
  {
    id: "service_unr_housing",
    title: "Campus housing and room assignments",
    description: "Find campus housing deadlines, room assignments, and residence life information for UNR students.",
    category: "Housing",
    externalLink: "https://www.unr.edu/housing",
    jurisdictionId: "unr-campus",
    jurisdictionName: "University of Nevada, Reno",
    responsibleEntity: "UNR Residential Life, Housing and Food Services",
    responsibleOfficialId: null,
    relatedIssue: "Campus housing",
    createdAt: "2026-04-01T08:49:00.000Z",
  },
  {
    id: "service_unr_wellness",
    title: "Counseling and wellness",
    description: "Access UNR counseling, student wellness, and mental health support resources.",
    category: "Public Safety",
    externalLink: "https://www.unr.edu/counseling",
    jurisdictionId: "unr-campus",
    jurisdictionName: "University of Nevada, Reno",
    responsibleEntity: "UNR Counseling Services",
    responsibleOfficialId: null,
    relatedIssue: "Student wellness",
    createdAt: "2026-04-01T08:51:00.000Z",
  },
  {
    id: "service_unr_transportation",
    title: "Parking and transportation",
    description: "Use campus parking, transit, and commuting information for UNR students and staff.",
    category: "Transportation",
    externalLink: "https://www.unr.edu/parking-and-transportation",
    jurisdictionId: "unr-campus",
    jurisdictionName: "University of Nevada, Reno",
    responsibleEntity: "UNR Parking and Transportation Services",
    responsibleOfficialId: null,
    relatedIssue: "Late-night transit",
    createdAt: "2026-04-01T08:53:00.000Z",
  },
  {
    id: "service_unlv_registrar",
    title: "Registrar and enrollment support",
    description: "Find enrollment, registration, transcript, and academic calendar help through UNLV registrar resources.",
    category: "Education",
    externalLink: "https://www.unlv.edu/registrar",
    jurisdictionId: "unlv-campus",
    jurisdictionName: "University of Nevada, Las Vegas",
    responsibleEntity: "UNLV Office of the Registrar",
    responsibleOfficialId: null,
    relatedIssue: "Enrollment and registration",
    createdAt: "2026-04-01T08:55:00.000Z",
  },
  {
    id: "service_unlv_financial_aid",
    title: "Financial aid and scholarships",
    description: "Use UNLV financial aid resources for FAFSA support, scholarships, and student account guidance.",
    category: "Education",
    externalLink: "https://www.unlv.edu/finaid",
    jurisdictionId: "unlv-campus",
    jurisdictionName: "University of Nevada, Las Vegas",
    responsibleEntity: "UNLV Financial Aid and Scholarships",
    responsibleOfficialId: null,
    relatedIssue: "Student affordability",
    createdAt: "2026-04-01T08:57:00.000Z",
  },
  {
    id: "service_unlv_housing",
    title: "Campus housing and residence life",
    description: "Find housing deadlines, room assignments, and residence life information for UNLV students.",
    category: "Housing",
    externalLink: "https://www.unlv.edu/housing",
    jurisdictionId: "unlv-campus",
    jurisdictionName: "University of Nevada, Las Vegas",
    responsibleEntity: "UNLV Housing and Residential Life",
    responsibleOfficialId: null,
    relatedIssue: "Campus housing",
    createdAt: "2026-04-01T08:59:00.000Z",
  },
  {
    id: "service_unlv_wellness",
    title: "Counseling and wellness",
    description: "Access UNLV counseling, wellness, and student care resources.",
    category: "Public Safety",
    externalLink: "https://www.unlv.edu/caps",
    jurisdictionId: "unlv-campus",
    jurisdictionName: "University of Nevada, Las Vegas",
    responsibleEntity: "UNLV Student Counseling and Psychological Services",
    responsibleOfficialId: null,
    relatedIssue: "Student wellness",
    createdAt: "2026-04-01T09:01:00.000Z",
  },
  {
    id: "service_unlv_transportation",
    title: "Parking and transportation",
    description: "Use campus parking and transportation resources for commuting and on-campus access.",
    category: "Transportation",
    externalLink: "https://www.unlv.edu/parking-services",
    jurisdictionId: "unlv-campus",
    jurisdictionName: "University of Nevada, Las Vegas",
    responsibleEntity: "UNLV Parking and Transportation Services",
    responsibleOfficialId: null,
    relatedIssue: "Campus transportation",
    createdAt: "2026-04-01T09:03:00.000Z",
  },
  {
    id: "service_wnc_registrar",
    title: "Enrollment and admissions help",
    description: "Find admissions, enrollment, and student-records resources for Western Nevada College.",
    category: "Education",
    externalLink: "https://wnc.edu/admissions/",
    jurisdictionId: "wnc-campus",
    jurisdictionName: "Western Nevada College",
    responsibleEntity: "Western Nevada College Admissions and Records",
    responsibleOfficialId: null,
    relatedIssue: "Enrollment and registration",
    createdAt: "2026-04-01T09:05:00.000Z",
  },
  {
    id: "service_wnc_financial_aid",
    title: "Financial aid and student accounts",
    description: "Find WNC financial aid, scholarships, and tuition support resources.",
    category: "Education",
    externalLink: "https://wnc.edu/financial/",
    jurisdictionId: "wnc-campus",
    jurisdictionName: "Western Nevada College",
    responsibleEntity: "Western Nevada College Financial Aid",
    responsibleOfficialId: null,
    relatedIssue: "Student affordability",
    createdAt: "2026-04-01T09:07:00.000Z",
  },
  {
    id: "service_wnc_disability",
    title: "Disability services",
    description: "Find disability accommodation and student access resources for WNC.",
    category: "Education",
    externalLink: "https://wnc.edu/disability/",
    jurisdictionId: "wnc-campus",
    jurisdictionName: "Western Nevada College",
    responsibleEntity: "Western Nevada College Disability Support Services",
    responsibleOfficialId: null,
    relatedIssue: "Student access",
    createdAt: "2026-04-01T09:09:00.000Z",
  },
  {
    id: "service_wnc_career",
    title: "Career services",
    description: "Use WNC career planning, advising, and workforce support resources.",
    category: "Education",
    externalLink: "https://wnc.edu/career-services/",
    jurisdictionId: "wnc-campus",
    jurisdictionName: "Western Nevada College",
    responsibleEntity: "Western Nevada College Career Services",
    responsibleOfficialId: null,
    relatedIssue: "Workforce pathways",
    createdAt: "2026-04-01T09:11:00.000Z",
  },
];

function communityMatches(jurisdictionName: string, communityId: string) {
  const community = getCommunityById(communityId);

  if (!community) {
    return false;
  }

  return community.jurisdictionMatches.includes(jurisdictionName);
}

export function getServicesForCommunity(communityId: string, category?: ServiceCategory | "all") {
  return seededServices
    .filter((service) => communityMatches(service.jurisdictionName, communityId))
    .filter((service) => (category && category !== "all" ? service.category === category : true))
    .sort((a, b) => a.category.localeCompare(b.category) || a.title.localeCompare(b.title));
}

export function getTopServicesForCommunity(communityId: string, limit = 5) {
  return getServicesForCommunity(communityId).slice(0, limit);
}

export function getServiceCategories() {
  return ["Housing", "Education", "Transportation", "Permits", "Utilities", "Public Safety"] as const;
}
