import { DistrictType, JurisdictionType, OfficeLevel } from "@prisma/client";

import { buildOfficialsFoundation, officialsResult, type OfficialSeedRecord } from "@/lib/civic-data/adapters/foundation";
import { validateOfficialPages } from "@/lib/civic-data/adapters/official-page-records";
import type { CivicDataAdapter } from "@/lib/civic-data/types";

const records: OfficialSeedRecord[] = [
  {
    externalId: "nevada-us-senate-cortez-masto",
    fullName: "Catherine Cortez Masto",
    officeTitle: "U.S. Senator for Nevada",
    jurisdictionSlug: "nevada",
    jurisdictionName: "Nevada",
    jurisdictionType: JurisdictionType.STATE,
    officeExternalId: "nevada-us-senate-seat-1",
    districtExternalId: "nevada-at-large-federal",
    districtName: "Nevada At-Large",
    districtType: DistrictType.AT_LARGE,
    officeLevel: OfficeLevel.FEDERAL,
    partyText: "Democratic",
    websiteUrl: "https://www.cortezmasto.senate.gov/",
    phone: "(202) 224-3542",
    termStart: "2023-01-03",
    termEnd: "2029-01-03",
    parentJurisdictionSlug: "united-states",
  },
  {
    externalId: "nevada-us-senate-rosen",
    fullName: "Jacky Rosen",
    officeTitle: "U.S. Senator for Nevada",
    jurisdictionSlug: "nevada",
    jurisdictionName: "Nevada",
    jurisdictionType: JurisdictionType.STATE,
    officeExternalId: "nevada-us-senate-seat-3",
    districtExternalId: "nevada-at-large-federal",
    districtName: "Nevada At-Large",
    districtType: DistrictType.AT_LARGE,
    officeLevel: OfficeLevel.FEDERAL,
    partyText: "Democratic",
    websiteUrl: "https://www.rosen.senate.gov/",
    phone: "(202) 224-6244",
    termStart: "2025-01-03",
    termEnd: "2031-01-03",
    parentJurisdictionSlug: "united-states",
  },
  {
    externalId: "nevada-us-house-1",
    fullName: "Dina Titus",
    officeTitle: "U.S. Representative for Nevada District 1",
    jurisdictionSlug: "nevada",
    jurisdictionName: "Nevada",
    jurisdictionType: JurisdictionType.STATE,
    officeExternalId: "nevada-us-house-office-1",
    districtExternalId: "nevada-congressional-district-1",
    districtName: "Congressional District 1",
    districtType: DistrictType.CONGRESSIONAL,
    officeLevel: OfficeLevel.FEDERAL,
    partyText: "Democratic",
    websiteUrl: "https://titus.house.gov/",
    phone: "(202) 225-5965",
    termStart: "2025-01-03",
    termEnd: "2027-01-03",
    parentJurisdictionSlug: "united-states",
  },
  {
    externalId: "nevada-us-house-2",
    fullName: "Mark Amodei",
    officeTitle: "U.S. Representative for Nevada District 2",
    jurisdictionSlug: "nevada",
    jurisdictionName: "Nevada",
    jurisdictionType: JurisdictionType.STATE,
    officeExternalId: "nevada-us-house-office-2",
    districtExternalId: "nevada-congressional-district-2",
    districtName: "Congressional District 2",
    districtType: DistrictType.CONGRESSIONAL,
    officeLevel: OfficeLevel.FEDERAL,
    partyText: "Republican",
    websiteUrl: "https://amodei.house.gov/",
    phone: "(202) 225-6155",
    termStart: "2025-01-03",
    termEnd: "2027-01-03",
    parentJurisdictionSlug: "united-states",
  },
  {
    externalId: "nevada-us-house-3",
    fullName: "Susie Lee",
    officeTitle: "U.S. Representative for Nevada District 3",
    jurisdictionSlug: "nevada",
    jurisdictionName: "Nevada",
    jurisdictionType: JurisdictionType.STATE,
    officeExternalId: "nevada-us-house-office-3",
    districtExternalId: "nevada-congressional-district-3",
    districtName: "Congressional District 3",
    districtType: DistrictType.CONGRESSIONAL,
    officeLevel: OfficeLevel.FEDERAL,
    partyText: "Democratic",
    websiteUrl: "https://susielee.house.gov/",
    phone: "(202) 225-3252",
    termStart: "2025-01-03",
    termEnd: "2027-01-03",
    parentJurisdictionSlug: "united-states",
  },
  {
    externalId: "nevada-us-house-4",
    fullName: "Steven Horsford",
    officeTitle: "U.S. Representative for Nevada District 4",
    jurisdictionSlug: "nevada",
    jurisdictionName: "Nevada",
    jurisdictionType: JurisdictionType.STATE,
    officeExternalId: "nevada-us-house-office-4",
    districtExternalId: "nevada-congressional-district-4",
    districtName: "Congressional District 4",
    districtType: DistrictType.CONGRESSIONAL,
    officeLevel: OfficeLevel.FEDERAL,
    partyText: "Democratic",
    websiteUrl: "https://horsford.house.gov/",
    phone: "(202) 225-9894",
    termStart: "2025-01-03",
    termEnd: "2027-01-03",
    parentJurisdictionSlug: "united-states",
  },
];

export const nevadaFederalDelegationAdapter: CivicDataAdapter = {
  key: "nevada-federal-delegation",
  displayName: "Nevada Federal Delegation",
  supportsIncremental: true,
  supportsScheduled: true,
  async sync(context) {
    const issues = await validateOfficialPages(records);

    return officialsResult({
      sourceSlug: context.source.slug,
      cursor: new Date().toISOString(),
      data: buildOfficialsFoundation(records),
      issues,
    });
  },
};

