import type { AuthUser } from "@/types/domain";

export const seedUsers: AuthUser[] = [
  {
    id: "user_guest_browse",
    email: "guest@directdemocracy.local",
    name: "Guest Browser",
    username: "guest",
    bio: "Read-only public browsing session.",
    role: "citizen",
    verificationState: "unverified",
    jurisdictionName: "Nevada",
    followerCount: 0,
    isVerifiedVoter: false,
    isAnonymousPublic: true,
  },
  {
    id: "user_citizen_alicia_hart",
    email: "alicia.hart@directdemocracy.local",
    name: "Alicia Hart",
    username: "aliciahart",
    bio: "Carson City resident following school funding, downtown growth, and water planning.",
    role: "citizen",
    verificationState: "voterVerified",
    jurisdictionName: "Carson City, Nevada",
    followerCount: 184,
    isVerifiedVoter: true,
    isAnonymousPublic: true,
  },
  {
    id: "user_citizen_miles_reed",
    email: "miles.reed@directdemocracy.local",
    name: "Miles Reed",
    username: "milesreed",
    bio: "Washoe County resident focused on transit reliability, wildfire preparedness, and housing costs.",
    role: "citizen",
    verificationState: "unverified",
    jurisdictionName: "Washoe County, Nevada",
    followerCount: 92,
    isVerifiedVoter: false,
    isAnonymousPublic: true,
  },
  {
    id: "user_citizen_tiana_moore",
    email: "tiana.moore@directdemocracy.local",
    name: "Tiana Moore",
    username: "tianamoore",
    bio: "Campus-verified UNR user tracking campaign finance, education funding, and land use policy.",
    role: "citizen",
    verificationState: "unverified",
    studentModeEnabled: true,
    studentVerified: true,
    studentEmail: "tiana.moore@unr.edu",
    studentCampusCommunityId: "unr-campus",
    jurisdictionName: "Nevada",
    followerCount: 133,
    isVerifiedVoter: false,
    isAnonymousPublic: false,
  },
  {
    id: "user_citizen_casey_rivera",
    email: "casey.rivera@directdemocracy.local",
    name: "Casey Rivera",
    username: "caseyrivera",
    bio: "New Direct Democracy user setting up a profile and choosing initial issues.",
    role: "citizen",
    verificationState: "unverified",
    jurisdictionName: "Nevada",
    followerCount: 0,
    isVerifiedVoter: false,
    isAnonymousPublic: true,
  },
  {
    id: "user_citizen_daniel_rowe",
    email: "daniel.rowe@directdemocracy.local",
    name: "Daniel Rowe",
    username: "danielrowe",
    bio: "Citizen account awaiting identity-based candidate profile matching.",
    role: "citizen",
    verificationState: "voterVerified",
    jurisdictionName: "Nevada",
    followerCount: 0,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_citizen_aaron_hale",
    email: "aaron.hale@directdemocracy.local",
    name: "Aaron Hale",
    username: "aaronhale",
    bio: "Citizen account awaiting identity-based official profile matching.",
    role: "citizen",
    verificationState: "voterVerified",
    jurisdictionName: "Washoe County, Nevada",
    followerCount: 0,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_trusted_citizen_marco_silva",
    email: "marco.silva@directdemocracy.local",
    name: "Marco Silva",
    username: "marcosilva",
    bio: "Trusted Carson City community voice posting budget recaps and meeting notes.",
    role: "trustedCitizen",
    verificationState: "voterVerified",
    jurisdictionName: "Carson City, Nevada",
    followerCount: 12640,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_trusted_citizen_hannah_cho",
    email: "hannah.cho@directdemocracy.local",
    name: "Hannah Cho",
    username: "hannahcho",
    bio: "Trusted Washoe County resident focused on growth, public meetings, and neighborhood infrastructure.",
    role: "trustedCitizen",
    verificationState: "voterVerified",
    jurisdictionName: "Washoe County, Nevada",
    followerCount: 10890,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_trusted_citizen_nora_patel",
    email: "nora.patel@directdemocracy.local",
    name: "Nora Patel",
    username: "norapatel",
    bio: "Trusted Nevada civic explainer focused on healthcare costs, energy policy, and federal-state budget tradeoffs.",
    role: "trustedCitizen",
    verificationState: "voterVerified",
    jurisdictionName: "Nevada",
    followerCount: 6210,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_candidate_sofia_bennett",
    email: "sofia.bennett@directdemocracy.local",
    name: "Sofia Bennett",
    username: "sofiabennett",
    bio: "Candidate for Nevada Governor focused on water resilience, housing delivery, and public accountability.",
    role: "candidate",
    verificationState: "voterVerified",
    jurisdictionName: "Nevada",
    followerCount: 9650,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_candidate_owen_castillo",
    email: "owen.castillo@directdemocracy.local",
    name: "Owen Castillo",
    username: "owencastillo",
    bio: "Candidate for Carson City School Board focused on classroom support, teacher retention, and transparent budgeting.",
    role: "candidate",
    verificationState: "voterVerified",
    jurisdictionName: "Carson City, Nevada",
    followerCount: 4180,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_candidate_ava_marquette",
    email: "ava.marquette@directdemocracy.local",
    name: "Ava Marquette",
    username: "avamarquette",
    bio: "Presidential candidate focused on housing supply, healthcare affordability, education access, and ethics reform.",
    role: "candidate",
    verificationState: "voterVerified",
    jurisdictionName: "United States",
    followerCount: 42800,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_candidate_luke_holloway",
    email: "luke.holloway@directdemocracy.local",
    name: "Luke Holloway",
    username: "lukeholloway",
    bio: "Presidential candidate focused on energy reliability, tax restraint, public safety, and domestic manufacturing.",
    role: "candidate",
    verificationState: "voterVerified",
    jurisdictionName: "United States",
    followerCount: 39650,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_candidate_maya_ortega",
    email: "maya.ortega@directdemocracy.local",
    name: "Maya Ortega",
    username: "mayaortega",
    bio: "Candidate for U.S. Senate in Nevada focused on cost of living, healthcare access, and public lands resilience.",
    role: "candidate",
    verificationState: "voterVerified",
    jurisdictionName: "Nevada",
    followerCount: 15840,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_candidate_cole_wyatt",
    email: "cole.wyatt@directdemocracy.local",
    name: "Cole Wyatt",
    username: "colewyatt",
    bio: "Candidate for U.S. Senate in Nevada focused on energy production, taxes, public safety, and business growth.",
    role: "candidate",
    verificationState: "voterVerified",
    jurisdictionName: "Nevada",
    followerCount: 14220,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_official_elena_ramirez",
    email: "elena.ramirez@directdemocracy.local",
    name: "Elena Ramirez",
    username: "elenaramirez",
    bio: "Carson City mayor posting updates on budgets, housing, and downtown infrastructure.",
    role: "official",
    verificationState: "voterVerified",
    jurisdictionName: "Carson City, Nevada",
    followerCount: 21420,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_official_david_park",
    email: "david.park@directdemocracy.local",
    name: "David Park",
    username: "davidpark",
    bio: "Washoe County commissioner focused on land use, roads, and emergency readiness.",
    role: "official",
    verificationState: "voterVerified",
    jurisdictionName: "Washoe County, Nevada",
    followerCount: 12840,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_official_adrian_castillo",
    email: "adrian.castillo@directdemocracy.local",
    name: "Adrian Castillo",
    username: "adriancastillo",
    bio: "Nevada member of Congress posting vote explainers on housing, healthcare costs, ethics reform, and veterans services.",
    role: "official",
    verificationState: "voterVerified",
    jurisdictionName: "Nevada's 3rd Congressional District",
    followerCount: 58240,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_media_nevada_public_signal",
    email: "newsroom@nevadapublicsignal.demo",
    name: "Nevada Public Signal",
    username: "nevadapublicsignal",
    bio: "Statewide demo newsroom covering Nevada policy, elections, water, housing, and public finance.",
    role: "media",
    verificationState: "voterVerified",
    mediaTier: "trustedSource",
    jurisdictionName: "Nevada",
    followerCount: 31840,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_media_carson_civic_watch",
    email: "editor@carsoncivicwatch.demo",
    name: "Carson Civic Watch",
    username: "carsoncivicwatch",
    bio: "Independent Carson City demo outlet focused on city hall, schools, local services, and public meetings.",
    role: "media",
    verificationState: "voterVerified",
    mediaTier: "verifiedMedia",
    jurisdictionName: "Carson City, Nevada",
    followerCount: 7840,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
  {
    id: "user_admin_riley_morgan",
    email: "admin@directdemocracy.local",
    name: "Riley Morgan",
    username: "rileymorgan",
    bio: "Admin managing platform operations, moderation policy, and demo profile seeding.",
    role: "admin",
    verificationState: "voterVerified",
    jurisdictionName: "Nevada",
    followerCount: 120,
    isVerifiedVoter: true,
    isAnonymousPublic: false,
  },
];

export function getSeedUserById(id: string | undefined) {
  return seedUsers.find((user) => user.id === id);
}

export function getDefaultSeedUser() {
  return seedUsers.find((user) => user.id === "user_citizen_alicia_hart") ?? seedUsers[0];
}
